#!/usr/bin/env python3
"""Inline shared tool CSS/JS into each standalone tool page.

Why this exists: every deployed .html must be self-contained with zero
runtime fetches (TOOLS.md golden rule 8), but hand-copying the shared
block between tools caused real drift -- divergent DPR caps, palettes and
frame caps between two files written in the same week. This script keeps
one source of truth without adding a runtime dependency.

Usage:
    python3 tools/build.py           # rewrite tool pages in place
    python3 tools/build.py --check   # exit 1 if any page is stale
    python3 tools/build.py --list    # show which pages have blocks

Edit tools/_shared.css and tools/_shared.js, then re-run. Never edit the
inlined copy inside a tool page -- it is overwritten.

Tool pages opt in by containing marker pairs:

    <!-- VIZ:CSS -->  ... generated ...  <!-- /VIZ:CSS -->
    <!-- VIZ:JS -->   ... generated ...  <!-- /VIZ:JS -->

Everything outside the markers is left byte-for-byte untouched, so a
tool's own styles and physics are never at risk.
"""

import argparse
import hashlib
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SHARED_CSS = ROOT / "tools" / "_shared.css"
SHARED_JS = ROOT / "tools" / "_shared.js"

# Pages to process. Tool pages only -- index.html has its own styles and
# is deliberately not part of the shared-runtime system.
TOOL_GLOBS = ("*-visualizer.html", "*-explorer.html")

BANNER = (
    "  /* GENERATED by tools/build.py from {src} -- DO NOT EDIT HERE.\n"
    "     Edit that file and re-run: python3 tools/build.py */"
)


def _block_re(tag):
    """Match a marker pair and everything between it, non-greedily."""
    return re.compile(
        r"(?P<open><!--\s*VIZ:%s\s*-->)"
        r"(?P<body>.*?)"
        r"(?P<close><!--\s*/VIZ:%s\s*-->)" % (tag, tag),
        re.DOTALL,
    )


CSS_RE = _block_re("CSS")
JS_RE = _block_re("JS")


def _indent(text, pad="  "):
    out = []
    for line in text.splitlines():
        out.append(pad + line if line.strip() else line)
    return "\n".join(out)


def render_css(shared_css):
    banner = BANNER.format(src="tools/_shared.css")
    return "\n<style>\n%s\n%s\n</style>\n" % (banner, _indent(shared_css))


def render_js(shared_js):
    banner = BANNER.format(src="tools/_shared.js")
    return "\n<script>\n%s\n%s\n</script>\n" % (banner, _indent(shared_js))


def apply(text, shared_css, shared_js):
    """Replace marker block contents. Returns (new_text, n_blocks)."""
    n = 0

    def css_sub(m):
        nonlocal n
        n += 1
        return m.group("open") + render_css(shared_css) + m.group("close")

    def js_sub(m):
        nonlocal n
        n += 1
        return m.group("open") + render_js(shared_js) + m.group("close")

    text = CSS_RE.sub(css_sub, text)
    text = JS_RE.sub(js_sub, text)
    return text, n


def tool_pages():
    seen = set()
    for pattern in TOOL_GLOBS:
        for p in sorted(ROOT.glob(pattern)):
            if p not in seen:
                seen.add(p)
                yield p


def digest(s):
    return hashlib.sha256(s.encode("utf-8")).hexdigest()[:12]


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if any page is stale; write nothing")
    ap.add_argument("--list", action="store_true",
                    help="list tool pages and their marker status")
    args = ap.parse_args()

    for f in (SHARED_CSS, SHARED_JS):
        if not f.exists():
            sys.exit("missing shared source: %s" % f.relative_to(ROOT))

    shared_css = SHARED_CSS.read_text(encoding="utf-8").rstrip("\n")
    shared_js = SHARED_JS.read_text(encoding="utf-8").rstrip("\n")

    pages = list(tool_pages())
    if not pages:
        print("no tool pages found (looked for %s)" % ", ".join(TOOL_GLOBS))
        return 0

    stale, written, skipped = [], [], []

    for page in pages:
        rel = page.relative_to(ROOT)
        original = page.read_text(encoding="utf-8")
        updated, n = apply(original, shared_css, shared_js)

        if args.list:
            has_css = bool(CSS_RE.search(original))
            has_js = bool(JS_RE.search(original))
            print("  %-32s CSS:%s JS:%s" % (
                rel, "yes" if has_css else " no", "yes" if has_js else " no"))
            continue

        if n == 0:
            skipped.append(rel)
            continue

        if updated == original:
            continue

        if args.check:
            stale.append(rel)
            continue

        page.write_text(updated, encoding="utf-8")
        written.append(rel)

    if args.list:
        return 0

    if args.check:
        if stale:
            print("STALE (run: python3 tools/build.py)")
            for rel in stale:
                print("  %s" % rel)
            return 1
        print("up to date  [css %s, js %s]" % (digest(shared_css), digest(shared_js)))
        return 0

    for rel in written:
        print("  updated  %s" % rel)
    for rel in skipped:
        print("  skipped  %s  (no VIZ markers -- not yet migrated)" % rel)
    if not written:
        print("  all pages already up to date")
    return 0


if __name__ == "__main__":
    sys.exit(main())
